sapiVersion: apps/v1
kind: Deployment
metadata:
  name: ahmed
spec: 
  selector:
    matchLabels:
      app: ahmed
  replicas: 3
  template:
    metadata:
      name : pods
      labels:
        app: ahmed
    spec: 
      containers:
        - image: ahmed159753/os
          name: ahmed
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi "
